//
//  TransferModeCardView.swift
//  VisaActivity
//
//  Created by Pranoti Wakodkar on 23/01/26.
//

import SwiftUI
struct TransferModeCardView: View {
    let title: String
    let availableModes: [PickupMode]?
    // Binding to the selected mode (e.g. Air, Rail, Sea)
    @Binding var selectedMode: PickupMode?
    
    // Binding to the dynamic fields generated by the ViewModel
    @Binding var fields: [FormField]
    @Binding var showError: Bool
    
    @State private var isCollapsable: Bool = true
    
    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            // MARK: - Header Section
            Button {
                withAnimation {
                    isCollapsable.toggle()
                }
            } label: {
                HStack {
                    Text(title)
                        .font(.custom(Constants.Font.openSansBold, size: 12))
                        .foregroundColor(Color(hex: Constants.HexColors.blackStrong))
                    
                    Spacer()
                    
                    Image(systemName: isCollapsable ? "chevron.up" : "chevron.down")
                        .resizable()
                        .scaledToFit()
                        .frame(width: 14, height: 14)
                        .foregroundStyle(Color(hex: Constants.HexColors.primary))
                }
                .contentShape(Rectangle())
            }
            
            // MARK: - Collapsible Content
            if isCollapsable {
                VStack(alignment: .leading, spacing: 8) {
                        ZStack {
                            // Layer 1: Visual (Static)
                            // This ensures the border and background never flicker
                            HStack {
                                Text(selectedMode?.mode ?? "Select")
                                    .foregroundColor(selectedMode == nil ? .gray : .primary)
                                    .font(.custom(Constants.Font.openSansRegular, size: 14))
                                Spacer()
                                Image(systemName: "chevron.down")
                                    .font(.system(size: 12))
                                    .foregroundStyle(Color(hex: Constants.HexColors.primary))
                            }
                            .padding(12)
                            .background(
                                RoundedRectangle(cornerRadius: 8)
                                    .stroke(Color(hex: Constants.HexColors.neutralWeak), lineWidth: 1)
                            )
                            
                            
                            // Layer 2: Interaction (Invisible Menu)
                            // Captures the tap without affecting visuals
                            Menu {
                                ForEach(availableModes ?? [], id: \.mode) { option in
                                    Button {
                                        // Trigger ViewModel update
                                        selectedMode = option
                                    } label: {
                                        Text(option.mode ?? "")
                                    }
                                }
                            } label: {
                                Color.white.opacity(0.001)
                                    .frame(maxWidth: .infinity, maxHeight: .infinity)
                                    .contentShape(Rectangle())
                            }
                        }
                        if showError, selectedMode?.mode == nil {
                            Text("Please Select \(title)")
                                .font(.custom(Constants.Font.openSansRegular, size: 10))
                                .foregroundColor(Color(hex: Constants.HexColors.error))
                        }
                    }
                    
                    // 2. Dynamic Questions Form
                    // Only render if there are fields available
                    if !fields.isEmpty {
                        VStack(alignment: .leading, spacing: 12) {
                            
                            // Iterate through the binding array to allow editing
                            ForEach($fields) { $field in
                                FormFieldRenderer(field: $field)
                            }
                        }
                        // Smooth transition when fields appear/disappear
                        .transition(.opacity.combined(with: .move(edge: .top)))
                    }
                }
            }
        // Auto-expand the card when a user selects a mode
        .onChange(of: selectedMode?.mode) { newValue in
            if newValue != nil {
                withAnimation {
                    isCollapsable = true
                }
            }
        }
        .padding()
        .background(
            RoundedRectangle(cornerRadius: 12)
                .stroke(Color(hex: Constants.HexColors.neutralWeak), lineWidth: 1)
        )
        .clipShape(RoundedRectangle(cornerRadius: 12))
        }
    }


